# .goreleaser.yaml - GitHub Releases Configuration
# Enables cross-platform builds and automated release creation
version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

env:
  - GO111MODULE=auto
  - CGO_ENABLED=0

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  use: github
  groups:
    - title: 'Features'
      regexp: '^feat[\s].*'
      order: 100
    - title: 'Under the Hood'
      regexp: '^fix[\s].*|^perf[\s].*'
      order: 200
    - title: 'Other Changes'
      order: 300

builds:
  - id: sl
    main: ./cmd/sl/main.go
    binary: sl
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.buildType=release

archives:
  - formats:
      - tar.gz
    name_template: 'specledger_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - LICENSE
      - README.md

brews:
  - name: specledger
    homepage: 'https://github.com/specledger/specledger'
    description: 'Unified CLI for project bootstrap and specification dependency management'
    license: MIT
    repository:
      owner: specledger
      name: homebrew-specledger
    skip_upload: true
    # TODO: Set up separate homebrew-specledger tap repo with proper permissions

release:
  github:
    owner: specledger
    name: specledger
  prerelease: auto
  draft: false
  mode: replace
  header: |
    ## 🚀 SpecLedger {{ .Tag }}
  footer: |
    ## 📦 Installation

    ### Binary
    Download from the [releases page](https://github.com/specledger/specledger/releases/latest).

    ### Homebrew
    ```bash
    brew tap specledger/homebrew-specledger
    brew install specledger
    ```

    ### From source
    ```bash
    go install github.com/specledger/specledger/cmd/sl@latest
    ```

    ## 📚 Documentation

    - [Documentation](https://specledger.io/docs)
    - [GitHub Issues](https://github.com/specledger/specledger/issues)
    - [Changelog](https://github.com/specledger/specledger/blob/main/CHANGELOG.md)
